name: Azure VM Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          
      - name: Build 
        run: npm install && npm run build
        
      - name: Deploy to Azure VM
        run: |
          echo "$AZURE_SSH_PRIVATE_KEY" > ssh_key.pem
          chmod 400 ssh_key.pem
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem azureuser@mollydemo.japaneast.cloudapp.azure.com "rsync -avz --exclude='.git' --exclude='node_modules' ./ azureuser@mollydemo.japaneast.cloudapp.azure.com:/nest-practice"
        env:
          AZURE_SSH_PRIVATE_KEY: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}

      - name: Restart Pm2
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem azureuser@mollydemo.japaneast.cloudapp.azure.com "pm2 restart molly-demo"
        env:
          AZURE_SSH_PRIVATE_KEY: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}

